### ISSUE TITLE
Final group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by Alexr16** [Alexr16/Hotel-agent-back-end#21]
[GitHub Project ](https://github.com/users/Alexr16/projects/3/views/1)

We are 3 people on the team: @ahmedadel56, @sediqullahbadakhsh , and @Alexr16.
 
<img width="1431" alt="Screen Shot 2022-08-10 at 11 19 08" src="https://user-images.githubusercontent.com/95060298/183961648-724a294f-a3f0-40bb-a37a-c89e3bde5375.png">

**Comment by MuriloRoque** [comment]
Hi @Alexr16, @ahmedadel56, @sediqullahbadakhsh,

In my opinion, your project is complete!

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
